package com.hsbc.payment.enums;

public enum ErrorCode {
    VALIDATION_FAILED,
    INSUFFICIENT_FUNDS,
    INVALID_ACCOUNT,
    INVALID_CURRENCY,
    INVALID_AMOUNT,
    DUPLICATE_PAYMENT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND,
    PROCESSING_ERROR,
    NETWORK_ERROR,
    RISK_BLOCKED
}
