package com.hsbc.payment.enums;

public enum ErrorCode {
    VALIDATION_FAILED,
    INSUFFICIENT_FUNDS,
    INVALID_ACCOUNT,
    INVALID_CURRENCY,
    INVALID_AMOUNT,
    INVALID_CREDENTIALS,
    BENEFICIARY_MISMATCH,
    EXCHANGE_RATE_NOT_FOUND,
    DUPLICATE_ACCOUNT,
    DUPLICATE_PAYMENT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND,
    PROCESSING_ERROR,
    NETWORK_ERROR,
    RISK_BLOCKED,
    RETRY_EXHAUSTED
}
